// Generated by scripts/generate-build-info.ts at build time (prebuild).
// Do not edit — overwritten on every `next build`. Falls back to dev values
// when git is unavailable (non-git checkout, dev mode).
export const BUILD_COMMIT_HASH = "30337ab2";
export const BUILD_COMMIT_DATE = "2026-09-24T10:27:18+08:00";
