import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

function git(args: string): string {
  try {
    return execSync(`git ${args}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

const commitHash = git("rev-parse --short HEAD");
const commitDate = git("log -1 --format=%cI");

const outputPath = resolve(process.cwd(), "src/lib/build-info.ts");
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generate-build-info.ts at build time (prebuild).
// Do not edit — overwritten on every \`next build\`. Falls back to dev values
// when git is unavailable (non-git checkout, dev mode).
export const BUILD_COMMIT_HASH = ${JSON.stringify(commitHash)};
export const BUILD_COMMIT_DATE = ${JSON.stringify(commitDate)};
`
);

console.log(`build-info: commit ${commitHash || "(none)"} date ${commitDate || "(none)"}`);
